sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pbasson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pbasson/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'dockerreact'
  env: 'dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-735717935121'
  bucket_path: 'dockerreact'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
