sudo: required
services:
    - docker
    
before_install: 
    - docker build -t pbasson/docker-react -f Dockerfile.dev .
    
script:
    -   docker run pbasson/docker-react npm run test -- --coverage
